[[fields]]
field = "id"
sqlite.type = "BLOB"
description = "O identificador único da categoria (UUID)."
example = "b1c2d3e4-5f6a-7b8c-9d0e-1f2a3b4c5d6e"

[[fields]]
field = "categoria"
sqlite.type = "TEXT"
description = "O nome descritivo da categoria."
example = "Smartphones"
